pub mod dialect;
pub mod nominal;
pub mod orthography;
pub mod upos;
pub mod verb;

#[cfg(test)]
pub mod tests;

use harper_brill::UPOS;
use is_macro::Is;
use paste::paste;
use serde::{Deserialize, Serialize};

use crate::{
    dict_word_metadata::{
        dialect::DialectFlags,
        nominal::{NounData, Person, PronounData},
        orthography::OrthFlags,
        verb::{VerbData, VerbFormFlags},
    },
    spell::WordId,
};

/// This represents a "lexeme" or "headword" which is case-folded but affix-expanded.
/// So not only lemmata but also inflected forms are stored here, with "horn" and "horns" each
/// having their own lexeme, but "Ivy" and "ivy" sharing the same lexeme.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize, PartialOrd, Hash)]
pub struct DictWordMetadata {
    /// The main parts of speech which have extra data.
    pub noun: Option<NounData>,
    pub pronoun: Option<PronounData>,
    pub verb: Option<VerbData>,
    pub adjective: Option<AdjectiveData>,
    pub adverb: Option<AdverbData>,
    pub conjunction: Option<ConjunctionData>,
    pub determiner: Option<DeterminerData>,
    pub affix: Option<AffixData>,
    /// Parts of speech which don't have extra data.
    /// Whether the word is a [preposition](https://www.merriam-webster.com/dictionary/preposition).
    #[serde(default = "default_false")]
    pub preposition: bool,
    /// Whether the word is an offensive word.
    pub swear: Option<bool>,
    /// The dialects this word belongs to.
    /// If no dialects are defined, it can be assumed that the word is
    /// valid in all dialects of English.
    #[serde(default = "default_default")]
    pub dialects: DialectFlags,
    /// Orthographic information: letter case, spaces, hyphens, etc.
    #[serde(default = "OrthFlags::empty")]
    pub orth_info: OrthFlags,
    /// Whether the word is considered especially common.
    #[serde(default = "default_false")]
    pub common: bool,
    #[serde(default = "default_none")]
    pub derived_from: Option<WordId>,
    /// Generated by a chunker. Declares whether the word is a member of a nominal phrase. Using
    /// this should be preferred over the similarly named `Pattern`.
    ///
    /// For more details, see [the announcement blog post](https://elijahpotter.dev/articles/training_a_chunker_with_burn).
    pub np_member: Option<bool>,
    /// Generated by a POS tagger. Declares what it inferred the word's part of speech to be.
    pub pos_tag: Option<UPOS>,
}

/// Needed for `serde`
fn default_false() -> bool {
    false
}

/// Needed for `serde`
fn default_none<T>() -> Option<T> {
    None
}

/// Needed for `serde`
fn default_default<T: Default>() -> T {
    T::default()
}

macro_rules! generate_metadata_queries {
    ($($category:ident has $($sub:ident),*).*) => {
        paste! {
            pub fn is_likely_homograph(&self) -> bool {
                [self.is_determiner(), self.preposition, $(
                    self.[< is_ $category >](),
                )*].iter().map(|b| *b as u8).sum::<u8>() > 1
            }

            /// How different is this word from another?
            pub fn difference(&self, other: &Self) -> u32 {
                [
                    $(
                        Self::[< is_ $category >],
                        $(
                            Self::[< is_ $sub _ $category >],
                            Self::[< is_non_ $sub _ $category >],
                        )*
                    )*
                ]
                .iter()
                .fold(0, |acc, func| acc + (func(self) ^ func(other)) as u32)
            }

            $(
                #[doc = concat!("Checks if the word is definitely a ", stringify!($category), ".")]
                pub fn [< is_ $category >](&self) -> bool {
                    self.$category.is_some()
                }

                $(
                    #[doc = concat!("Checks if the word is definitely a ", stringify!($category), " and more specifically is labeled as (a) ", stringify!($sub), ".")]
                    pub fn [< is_ $sub _ $category >](&self) -> bool {
                        matches!(
                            self.$category,
                            Some([< $category:camel Data >]{
                                [< is_ $sub >]: Some(true),
                                ..
                            })
                        ) }

                    #[doc = concat!("Checks if the word is definitely a ", stringify!($category), " and more specifically is labeled as __not__ (a) ", stringify!($sub), ".")]
                    pub fn [< is_non_ $sub _ $category >](&self) -> bool {
                        matches!(
                            self.$category,
                            Some([< $category:camel Data >]{
                                [< is_ $sub >]: None | Some(false),
                                ..
                            })
                        )
                    }
                )*
            )*
        }
    };
}

impl DictWordMetadata {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, other: &Self) -> Self {
        let mut clone = self.clone();
        clone.merge(other);
        clone
    }

    generate_metadata_queries!(
        // Singular and countable default to true, so their metadata queries are not generated.
        noun has proper, plural, mass, possessive.
        pronoun has personal, singular, plural, possessive, reflexive, subject, object.
        determiner has demonstrative, possessive, quantifier.
        verb has linking, auxiliary.
        conjunction has.
        adjective has.
        adverb has manner, frequency, degree
    );

    // Manual metadata queries

    // Pronoun metadata queries

    pub fn get_person(&self) -> Option<Person> {
        self.pronoun.as_ref().and_then(|p| p.person)
    }

    pub fn is_first_person_plural_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::First),
                is_plural: Some(true),
                ..
            })
        )
    }

    pub fn is_first_person_singular_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::First),
                is_singular: Some(true),
                ..
            })
        )
    }

    pub fn is_third_person_plural_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::Third),
                is_plural: Some(true),
                ..
            })
        )
    }

    pub fn is_third_person_singular_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::Third),
                is_singular: Some(true),
                ..
            })
        )
    }

    pub fn is_third_person_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::Third),
                ..
            })
        )
    }

    pub fn is_second_person_pronoun(&self) -> bool {
        matches!(
            self.pronoun,
            Some(PronounData {
                person: Some(Person::Second),
                ..
            })
        )
    }

    // Lemma is default if no verb form is specified in the dictionary
    pub fn is_verb_lemma(&self) -> bool {
        if let Some(verb) = self.verb {
            if let Some(forms) = verb.verb_forms {
                return forms.is_empty() || forms.contains(VerbFormFlags::LEMMA);
            } else {
                return true;
            }
        }
        false
    }

    pub fn is_verb_past_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms
                .is_some_and(|vf| vf.contains(VerbFormFlags::PAST))
        })
    }

    pub fn is_verb_regular_past_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms.is_some_and(|vf| {
                vf.contains(VerbFormFlags::PRETERITE) && vf.contains(VerbFormFlags::PAST_PARTICIPLE)
            })
        })
    }

    pub fn is_verb_simple_past_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms
                .is_some_and(|vf| vf.contains(VerbFormFlags::PRETERITE))
        })
    }

    pub fn is_verb_past_participle_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms
                .is_some_and(|vf| vf.contains(VerbFormFlags::PAST_PARTICIPLE))
        })
    }

    pub fn is_verb_simple_past_only(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms.is_some_and(|vf| {
                vf.contains(VerbFormFlags::PRETERITE)
                    && !vf.intersects(VerbFormFlags::PAST | VerbFormFlags::PAST_PARTICIPLE)
            })
        })
    }

    pub fn is_verb_past_participle_only(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms.is_some_and(|vf| {
                vf.contains(VerbFormFlags::PAST_PARTICIPLE)
                    && !vf.intersects(VerbFormFlags::PAST | VerbFormFlags::PRETERITE)
            })
        })
    }

    pub fn is_verb_progressive_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms
                .is_some_and(|vf| vf.contains(VerbFormFlags::PROGRESSIVE))
        })
    }

    pub fn is_verb_third_person_singular_present_form(&self) -> bool {
        self.verb.is_some_and(|v| {
            v.verb_forms
                .is_some_and(|vf| vf.contains(VerbFormFlags::THIRD_PERSON_SINGULAR))
        })
    }

    // Noun metadata queries

    // Singular is default if number is not marked in the dictionary.
    pub fn is_singular_noun(&self) -> bool {
        if let Some(noun) = self.noun {
            matches!(
                (noun.is_singular, noun.is_plural),
                (Some(true), _) | (None | Some(false), None | Some(false))
            )
        } else {
            false
        }
    }
    pub fn is_non_singular_noun(&self) -> bool {
        if let Some(noun) = self.noun {
            !matches!(
                (noun.is_singular, noun.is_plural),
                (Some(true), _) | (None | Some(false), None | Some(false))
            )
        } else {
            false
        }
    }

    // Countable is default if countability is not marked in the dictionary.
    pub fn is_countable_noun(&self) -> bool {
        if let Some(noun) = self.noun {
            matches!(
                (noun.is_countable, noun.is_mass),
                (Some(true), _) | (None | Some(false), None | Some(false))
            )
        } else {
            false
        }
    }
    pub fn is_non_countable_noun(&self) -> bool {
        if let Some(noun) = self.noun {
            !matches!(
                (noun.is_countable, noun.is_mass),
                (Some(true), _) | (None | Some(false), None | Some(false))
            )
        } else {
            false
        }
    }

    // Most mass nouns also have countable senses. Match those that are only mass nouns.
    pub fn is_mass_noun_only(&self) -> bool {
        if let Some(noun) = self.noun {
            matches!(
                (noun.is_countable, noun.is_mass),
                (None | Some(false), Some(true))
            )
        } else {
            false
        }
    }

    // Nominal metadata queries (noun + pronoun)

    /// Checks if the word is definitely nominal.
    pub fn is_nominal(&self) -> bool {
        self.is_noun() || self.is_pronoun()
    }

    /// Checks if the word is definitely a nominal and more specifically is labeled as (a) singular.
    pub fn is_singular_nominal(&self) -> bool {
        self.is_singular_noun() || self.is_singular_pronoun()
    }

    /// Checks if the word is definitely a nominal and more specifically is labeled as (a) plural.
    pub fn is_plural_nominal(&self) -> bool {
        self.is_plural_noun() || self.is_plural_pronoun()
    }

    /// Checks if the word is definitely a nominal and more specifically is labeled as (a) possessive.
    /// NOTE: `possessive pronoun`s are not qualifiers, but words like `mine`, `yours`, etc.
    /// The terminology of `possessive noun`, `possessive pronoun` and `possessive determiner` only
    /// tends to reinforce this confusion.
    pub fn is_possessive_nominal(&self) -> bool {
        self.is_possessive_noun() || self.is_possessive_determiner()
    }

    /// Checks if the word is definitely a nominal and more specifically is labeled as __not__ (a) singular.
    pub fn is_non_singular_nominal(&self) -> bool {
        self.is_non_singular_noun() || self.is_non_singular_pronoun()
    }

    /// Checks if the word is definitely a nominal and more specifically is labeled as __not__ (a) plural.
    pub fn is_non_plural_nominal(&self) -> bool {
        self.is_non_plural_noun() || self.is_non_plural_pronoun()
    }

    // Adjective metadata queries

    pub fn get_degree(&self) -> Option<Degree> {
        self.adjective.as_ref().and_then(|a| a.degree)
    }

    pub fn is_comparative_adjective(&self) -> bool {
        matches!(
            self.adjective,
            Some(AdjectiveData {
                degree: Some(Degree::Comparative)
            })
        )
    }

    pub fn is_superlative_adjective(&self) -> bool {
        matches!(
            self.adjective,
            Some(AdjectiveData {
                degree: Some(Degree::Superlative)
            })
        )
    }

    // Degree::Positive is the default if degree is not marked in the dictionary.
    pub fn is_positive_adjective(&self) -> bool {
        match self.adjective {
            Some(AdjectiveData {
                degree: Some(Degree::Positive),
            }) => true,
            Some(AdjectiveData { degree: None }) => true,
            Some(AdjectiveData {
                degree: Some(degree),
            }) => !matches!(degree, Degree::Comparative | Degree::Superlative),
            _ => false,
        }
    }

    // Determiner metadata queries

    // Checks if the word is definitely a determiner and more specifically is labeled as (a) quantifier.
    pub fn is_quantifier(&self) -> bool {
        self.is_quantifier_determiner()
    }

    // Non-POS queries

    /// Checks whether a word is _definitely_ a swear.
    pub fn is_swear(&self) -> bool {
        matches!(self.swear, Some(true))
    }

    // Orthographic queries

    /// Does the metadata for this word cover an all-lowercase variant? (e.g., "hello")
    ///
    /// This returns true if all letters in the word are lowercase. Words containing
    /// non-letter characters (like numbers or symbols) are only considered if all
    /// letter characters are lowercase.
    pub fn is_lowercase(&self) -> bool {
        self.orth_info.contains(OrthFlags::LOWERCASE)
    }
    /// Does the metadata for this word cover a titlecase variant? (e.g., "Hello")
    ///
    /// This returns true if the word is in titlecase form, which means:
    /// - The first letter is uppercase
    /// - All other letters are lowercase
    /// - The word is at least 2 characters long
    ///
    /// Examples: "Hello", "World"
    ///
    /// Note: Words with internal capital letters (like "McDonald") or apostrophes (like "O'Reilly")
    /// are not considered titlecase - they are classified as UPPER_CAMEL instead.
    pub fn is_titlecase(&self) -> bool {
        self.orth_info.contains(OrthFlags::TITLECASE)
    }
    /// Does the metadata for this word cover an all-uppercase variant? (e.g., "HELLO")
    ///
    /// This returns true if all letters in the word are uppercase. Words containing
    /// non-letter characters (like numbers or symbols) are only considered if all
    /// letter characters are uppercase.
    ///
    /// Examples: "HELLO", "NASA", "I"
    pub fn is_allcaps(&self) -> bool {
        self.orth_info.contains(OrthFlags::ALLCAPS)
    }
    /// Does the metadata for this word cover a lower camel case variant? (e.g., "helloWorld")
    ///
    /// This returns true if the word is in lower camel case, which means:
    /// - The first letter is lowercase
    /// - There is at least one uppercase letter after the first character
    /// - The word must be at least 2 characters long
    ///
    /// Examples: "helloWorld", "getHTTPResponse", "eBay"
    ///
    /// Note: Single words that are all lowercase will return false.
    /// Words starting with an uppercase letter will return false (those would be UpperCamel).
    pub fn is_lower_camel(&self) -> bool {
        self.orth_info.contains(OrthFlags::LOWER_CAMEL)
    }
    /// Does the metadata for this word cover an upper camel case / pascal case variant? (e.g., "HelloWorld")
    ///
    /// This returns true if the word is in upper camel case (also known as Pascal case), which means:
    /// - The first letter is uppercase
    /// - There is at least one other uppercase letter after the first character
    /// - There is at least one lowercase letter after the first uppercase letter
    /// - The word must be at least 3 characters long
    ///
    /// Examples:
    /// - "HelloWorld" (standard Pascal case)
    /// - "McDonald" (name with internal caps)
    /// - "O'Reilly" (name with apostrophe and internal caps)
    /// - "HttpRequest" (initialism followed by word)
    ///
    /// Note: Single words that are titlecase (like "Hello") will return false.
    /// Words that are all uppercase (like "NASA") will also return false.
    pub fn is_upper_camel(&self) -> bool {
        self.orth_info.contains(OrthFlags::UPPER_CAMEL)
    }

    /// Does the metadata for this word cover an apostrophized variant? (e.g., "doesn't")
    pub fn is_apostrophized(&self) -> bool {
        self.orth_info.contains(OrthFlags::APOSTROPHE)
    }

    pub fn is_roman_numerals(&self) -> bool {
        self.orth_info.contains(OrthFlags::ROMAN_NUMERALS)
    }

    /// Same thing as [`Self::or`], except in-place rather than a clone.
    pub fn merge(&mut self, other: &Self) -> &mut Self {
        macro_rules! merge {
            ($a:expr, $b:expr) => {
                match ($a, $b) {
                    (Some(a), Some(b)) => Some(a.or(&b)),
                    (Some(a), None) => Some(a),
                    (None, Some(b)) => Some(b),
                    (None, None) => None,
                }
            };
        }

        self.noun = merge!(self.noun, other.noun);
        self.pronoun = merge!(self.pronoun, other.pronoun);
        self.verb = merge!(self.verb, other.verb);
        self.adjective = merge!(self.adjective, other.adjective);
        self.adverb = merge!(self.adverb, other.adverb);
        self.conjunction = merge!(self.conjunction, other.conjunction);
        self.determiner = merge!(self.determiner, other.determiner);
        self.affix = merge!(self.affix, other.affix);
        self.preposition |= other.preposition;
        self.dialects |= other.dialects;
        self.orth_info |= other.orth_info;
        self.swear = self.swear.or(other.swear);
        self.common |= other.common;
        self.derived_from = self.derived_from.or(other.derived_from);
        self.pos_tag = self.pos_tag.or(other.pos_tag);
        self.np_member = self.np_member.or(other.np_member);

        self
    }
}

/// Additional metadata for determiners
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, Default)]
pub struct DeterminerData {
    pub is_demonstrative: Option<bool>,
    pub is_possessive: Option<bool>,
    pub is_quantifier: Option<bool>,
}

impl DeterminerData {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, other: &Self) -> Self {
        Self {
            is_demonstrative: self.is_demonstrative.or(other.is_demonstrative),
            is_possessive: self.is_possessive.or(other.is_possessive),
            is_quantifier: self.is_quantifier.or(other.is_quantifier),
        }
    }
}

/// Degree is a property of adjectives: positive is not inflected
/// Comparative is inflected with -er or comes after the word "more"
/// Superlative is inflected with -est or comes after the word "most"
#[derive(Debug, Copy, Clone, PartialEq, Eq, Serialize, Deserialize, PartialOrd, Is, Hash)]
pub enum Degree {
    Positive,
    Comparative,
    Superlative,
}

/// Some adjectives are not comparable so don't have -er or -est forms and can't be used with "more" or "most".
/// Some adjectives can only be used "attributively" (before a noun); some only predicatively (after "is" etc.).
/// In old grammars words like the articles and determiners are classified as adjectives but behave differently.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, Default)]
pub struct AdjectiveData {
    pub degree: Option<Degree>,
}

impl AdjectiveData {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, other: &Self) -> Self {
        Self {
            degree: self.degree.or(other.degree),
        }
    }
}

/// Adverb can be a "junk drawer" category for words which don't fit the other major categories.
/// The typical adverbs are "adverbs of manner", those derived from adjectives in -ly
/// other adverbs (time, place, etc) should probably not be considered adverbs for Harper's purposes
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, Default)]
pub struct AdverbData {
    pub is_manner: Option<bool>,
    pub is_frequency: Option<bool>,
    pub is_degree: Option<bool>,
}

impl AdverbData {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, _other: &Self) -> Self {
        Self {
            is_manner: self.is_manner.or(_other.is_manner),
            is_frequency: self.is_frequency.or(_other.is_frequency),
            is_degree: self.is_degree.or(_other.is_degree),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, Default)]
pub struct ConjunctionData {}

impl ConjunctionData {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, _other: &Self) -> Self {
        Self {}
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, Default)]
pub struct AffixData {
    pub is_prefix: Option<bool>,
    pub is_suffix: Option<bool>,
}

impl AffixData {
    /// Produce a copy of `self` with the known properties of `other` set.
    pub fn or(&self, _other: &Self) -> Self {
        Self {
            is_prefix: self.is_prefix.or(_other.is_prefix),
            is_suffix: self.is_suffix.or(_other.is_suffix),
        }
    }
}
