#![doc = include_str!("../README.md")]

use std::fs;
use std::path::Path;

struct PropertyMeta {
    name: String,
}

struct StructMeta {
    name: String,
    properties: Vec<PropertyMeta>,
}

fn main() {
    // Path to the file where harper-core keeps these data structures
    let target_file = "./harper-core/src/dict_word_metadata.rs";

    if !Path::new(target_file).exists() {
        eprintln!("Error: Target file not found at path: {}", target_file);
        std::process::exit(1);
    }

    let content = fs::read_to_string(target_file).expect("Failed to read source file");
    let ast = syn::parse_file(&content).expect("Failed to parse Rust syntax");

    let mut detected_structs = Vec::new();

    // 1. Gather all structures ending in "Data" and count their Option<bool> fields
    for item in ast.items {
        if let syn::Item::Struct(item_struct) = item {
            let struct_name = item_struct.ident.to_string();

            if !struct_name.ends_with("Data") {
                continue;
            }

            let mut properties = Vec::new();

            for field in item_struct.fields {
                if is_option_bool(&field.ty) {
                    if let Some(ident) = field.ident {
                        properties.push(PropertyMeta {
                            name: ident.to_string(),
                        });
                    }
                }
            }

            detected_structs.push(StructMeta {
                name: struct_name,
                properties,
            });
        }
    }

    // 2. Generate the Analysis Report & Schematic
    println!("=== POSSLQ COMBINATORIAL SCHEMATIC BUILDER ===\n");

    for s in &detected_structs {
        let pos_name = s.name.strip_suffix("Data").unwrap_or(&s.name);
        let property_count = s.properties.len();
        let bits_required = property_count * 2;
        let bytes_required = (bits_required + 7) / 8; // Ceil division

        println!("POS Variant: {}", pos_name);
        println!("  - Total Option<bool> Properties: {}", property_count);
        println!(
            "  - Bitfield Width Required: {} bits ({} bytes)",
            bits_required, bytes_required
        );

        // Print the layout map inside the bitfield
        for (index, prop) in s.properties.iter().push_into_index_loop() {
            let bit_offset = index * 2;
            println!(
                "    [{:02}..{:02}] -> {}",
                bit_offset,
                bit_offset + 1,
                prop.name
            );
        }
        println!();
    }

    // 3. Sketch out what the autogenerated Enum will look like in memory
    println!("--- Draft of the Autogenerated Runtime Enum ---");
    println!("pub enum PosslqPropertyField {{");
    for s in &detected_structs {
        let pos_name = s.name.strip_suffix("Data").unwrap_or(&s.name);
        let bits_required = s.properties.len() * 2;

        // Pick the smallest integer backing size for the payload
        let storage_type = match bits_required {
            0..=8 => "u8",
            9..=16 => "u16",
            17..=32 => "u32",
            _ => "u64",
        };
        println!("    {}({}),", pos_name, storage_type);
    }
    println!("}}");
}

fn is_option_bool(ty: &syn::Type) -> bool {
    if let syn::Type::Path(type_path) = ty {
        if let Some(segment) = type_path.path.segments.last() {
            if segment.ident == "Option" {
                if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                    if let Some(syn::GenericArgument::Type(syn::Type::Path(inner_path))) =
                        args.args.first()
                    {
                        return inner_path.path.is_ident("bool");
                    }
                }
            }
        }
    }
    false
}

// Quick polyfill trick to cleanly get indices in our preview loop
trait IndexIterExt: Iterator {
    fn push_into_index_loop(self) -> std::iter::Enumerate<Self>
    where
        Self: Sized,
    {
        self.enumerate()
    }
}
impl<I: Iterator> IndexIterExt for I {}
